package com.demo.adtadmdiv;

import com.demo.adtadmdiv.BaseAdtAdmDiv;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdtAdmDiv extends BaseAdtAdmDiv<AdtAdmDiv> {
	public static final AdtAdmDiv dao = new AdtAdmDiv();
}
