package com.demo.adtadmdiv;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdtAdmDiv<M extends BaseAdtAdmDiv<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setPcode(java.lang.String pcode) {
		set("pcode", pcode);
	}

	public java.lang.String getPcode() {
		return get("pcode");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPauseFlagCode(java.lang.Boolean pauseFlagCode) {
		set("Pause_Flag_Code", pauseFlagCode);
	}

	public java.lang.Boolean getPauseFlagCode() {
		return get("Pause_Flag_Code");
	}

	public void setUsedFlagCode(java.lang.Boolean usedFlagCode) {
		set("Used_Flag_Code", usedFlagCode);
	}

	public java.lang.Boolean getUsedFlagCode() {
		return get("Used_Flag_Code");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("Create_Time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("Create_Time");
	}

	public void setStartUseDate(java.util.Date startUseDate) {
		set("Start_Use_Date", startUseDate);
	}

	public java.util.Date getStartUseDate() {
		return get("Start_Use_Date");
	}

}
