package io.kungfu.admin.modules.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.Date;

/**
 * Generated by KungFuPanda, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 用户编号默认手机号
	 */
	public void setUserCode(String userCode) {
		set("user_code", userCode);
	}

	public String getUserCode() {
		return getStr("user_code");
	}

	/**
	 * 用户名称
	 */
	public void setUserName(String userName) {
		set("user_name", userName);
	}

	public String getUserName() {
		return getStr("user_name");
	}

	/**
	 * 密码
	 */
	public void setPassword(String password) {
		set("password", password);
	}

	public String getPassword() {
		return getStr("password");
	}

	/**
	 * 部门编号
	 */
	public void setOrgCode(String orgCode) {
		set("org_code", orgCode);
	}

	public String getOrgCode() {
		return getStr("org_code");
	}

	/**
	 * 工号
	 */
	public void setJobNo(String jobNo) {
		set("job_no", jobNo);
	}

	public String getJobNo() {
		return getStr("job_no");
	}

	/**
	 * 职务 字典
	 */
	public void setPost(String post) {
		set("post", post);
	}

	public String getPost() {
		return getStr("post");
	}

	/**
	 * 性别 字典
	 */
	public void setSex(Integer sex) {
		set("sex", sex);
	}

	public Integer getSex() {
		return getInt("sex");
	}

	/**
	 * 手机号码
	 */
	public void setMobile(String mobile) {
		set("mobile", mobile);
	}

	public String getMobile() {
		return getStr("mobile");
	}

	/**
	 * EMAIL
	 */
	public void setEmail(String email) {
		set("email", email);
	}

	public String getEmail() {
		return getStr("email");
	}

	/**
	 * 家庭地址
	 */
	public void setAddress(String address) {
		set("address", address);
	}

	public String getAddress() {
		return getStr("address");
	}

	/**
	 * 登录错误次数
	 */
	public void setFailNum(Integer failNum) {
		set("fail_num", failNum);
	}

	public Integer getFailNum() {
		return getInt("fail_num");
	}

	/**
	 * 允许登录
	 */
	public void setAllowLogin(Boolean allowLogin) {
		set("allow_login", allowLogin);
	}

	public Boolean getAllowLogin() {
		return get("allow_login");
	}

	/**
	 * 允许登录时间
	 */
	public void setAllowLoginTime(Date allowLoginTime) {
		set("allow_login_time", allowLoginTime);
	}

	public Date getAllowLoginTime() {
		return getDate("allow_login_time");
	}

	/**
	 * 最后登录时间
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}

	public Date getLastLoginTime() {
		return getDate("last_login_time");
	}

	/**
	 * 创建人ID
	 */
	public void setCreateUserId(Long createUserId) {
		set("create_user_id", createUserId);
	}

	public Long getCreateUserId() {
		return getLong("create_user_id");
	}

	/**
	 * 创建人
	 */
	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}

	public String getCreateUser() {
		return getStr("create_user");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(Date createTime) {
		set("create_time", createTime);
	}

	public Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 更新人ID
	 */
	public void setUpdateUserId(Long updateUserId) {
		set("update_user_id", updateUserId);
	}

	public Long getUpdateUserId() {
		return getLong("update_user_id");
	}

	/**
	 * 更新人
	 */
	public void setUpdateUser(String updateUser) {
		set("update_user", updateUser);
	}

	public String getUpdateUser() {
		return getStr("update_user");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(Date updateTime) {
		set("update_time", updateTime);
	}

	public Date getUpdateTime() {
		return getDate("update_time");
	}

}