package io.kungfu.admin.modules.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.Date;

/**
 * Generated by KungFuPanda, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 上级编码
	 */
	public void setParentCode(String parentCode) {
		set("parent_code", parentCode);
	}

	public String getParentCode() {
		return getStr("parent_code");
	}

	/**
	 * 上级名称
	 */
	public void setParentName(String parentName) {
		set("parent_name", parentName);
	}

	public String getParentName() {
		return getStr("parent_name");
	}

	/**
	 * 编码
	 */
	public void setMenuCode(String menuCode) {
		set("menu_code", menuCode);
	}

	public String getMenuCode() {
		return getStr("menu_code");
	}

	/**
	 * 功能名称
	 */
	public void setMenuName(String menuName) {
		set("menu_name", menuName);
	}

	public String getMenuName() {
		return getStr("menu_name");
	}

	/**
	 * 是否启用(1:是,0:否)
	 */
	public void setIsEnabled(Boolean isEnabled) {
		set("is_enabled", isEnabled);
	}

	public Boolean getIsEnabled() {
		return get("is_enabled");
	}

	/**
	 * 菜单地址
	 */
	public void setLinkPage(String linkPage) {
		set("link_page", linkPage);
	}

	public String getLinkPage() {
		return getStr("link_page");
	}

	/**
	 * 菜单类型(0:菜单,1:按钮)
	 */
	public void setMenuType(Integer menuType) {
		set("menu_type", menuType);
	}

	public Integer getMenuType() {
		return getInt("menu_type");
	}

	/**
	 * 图标
	 */
	public void setIcon(String icon) {
		set("icon", icon);
	}

	public String getIcon() {
		return getStr("icon");
	}

	/**
	 * 排序
	 */
	public void setDisplayNo(Integer displayNo) {
		set("display_no", displayNo);
	}

	public Integer getDisplayNo() {
		return getInt("display_no");
	}

	/**
	 * 注释
	 */
	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return getStr("remark");
	}

	/**
	 * 组件名称
	 */
	public void setComponent(String component) {
		set("component", component);
	}

	public String getComponent() {
		return getStr("component");
	}

	/**
	 * 创建人ID
	 */
	public void setCreateUserId(Long createUserId) {
		set("create_user_id", createUserId);
	}

	public Long getCreateUserId() {
		return getLong("create_user_id");
	}

	/**
	 * 创建人
	 */
	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}

	public String getCreateUser() {
		return getStr("create_user");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(Date createTime) {
		set("create_time", createTime);
	}

	public Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 更新人ID
	 */
	public void setUpdateUserId(Long updateUserId) {
		set("update_user_id", updateUserId);
	}

	public Long getUpdateUserId() {
		return getLong("update_user_id");
	}

	/**
	 * 更新人
	 */
	public void setUpdateUser(String updateUser) {
		set("update_user", updateUser);
	}

	public String getUpdateUser() {
		return getStr("update_user");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(Date updateTime) {
		set("update_time", updateTime);
	}

	public Date getUpdateTime() {
		return getDate("update_time");
	}

}