package io.kungfu.admin.modules.system.model;
import io.kungfu.admin.modules.system.model.base.BaseSysDict;

/**
 * Generated by KungFuPanda.
 */
@SuppressWarnings("serial")
public class SysDict extends BaseSysDict<SysDict> {
    public static final SysDict dao = new SysDict().dao();
}
