package io.kungfu.admin.modules.system.model;
import io.kungfu.admin.modules.system.model.base.BaseSysDictItem;

/**
 * Generated by KungFuPanda.
 */
@SuppressWarnings("serial")
public class SysDictItem extends BaseSysDictItem<SysDictItem> {
    public static final SysDictItem dao = new SysDictItem().dao();
}
