package io.kungfu.admin.modules.system.model;
import io.kungfu.admin.modules.system.model.base.BaseSysLog;

/**
 * Generated by KungFuPanda.
 */
@SuppressWarnings("serial")
public class SysLog extends BaseSysLog<SysLog> {
    public static final SysLog dao = new SysLog().dao();
}
