package io.kungfu.admin.modules.system.model;
import io.kungfu.admin.modules.system.model.base.BaseSysRole;

/**
 * Generated by KungFuPanda.
 */
@SuppressWarnings("serial")
public class SysRole extends BaseSysRole<SysRole> {
    public static final SysRole dao = new SysRole().dao();
}
