package io.kungfu.admin.modules.system.model;
import io.kungfu.admin.modules.system.model.base.BaseSysRoleMenu;

/**
 * Generated by KungFuPanda.
 */
@SuppressWarnings("serial")
public class SysRoleMenu extends BaseSysRoleMenu<SysRoleMenu> {
    public static final SysRoleMenu dao = new SysRoleMenu().dao();
}
