package io.kungfu.admin.modules.system.model;
import io.kungfu.admin.modules.system.model.base.BaseSysUser;

/**
 * Generated by KungFuPanda.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
    public static final SysUser dao = new SysUser().dao();
}
