package #(basePackage).modules.#(moduleName).model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
#set(className=firstCharToUpperCase(toCamelCase(tableName)))
import java.util.Date;

/**
 * Generated by KungFuPanda, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class Base#(className)<M extends Base#(className)<M>> extends Model<M> implements IBean {

    #for(column : columnList)
    #set(columnName=(toCamelCase(column.column_name)))
    #set(upperCaseColumnName=firstCharToUpperCase(toCamelCase(column.column_name)))
    #set(javaType=toJavaType(column.data_type, column.column_type))
    #set(javaMethod=toJavaMethod(column.data_type, column.column_type))
	/**
	 * #(column.column_comment)
	 */
	public void set#(upperCaseColumnName)(#(javaType) #(columnName)) {
		set("#(column.column_name)", #(columnName));
	}

	public #(javaType) get#(upperCaseColumnName)() {
		return get#(javaMethod)("#(column.column_name)");
	}

    #end
}