package #(basePackage).modules.#(moduleName).model;
#set(className=firstCharToUpperCase(toCamelCase(tableName)))
import #(basePackage).modules.#(moduleName).model.base.Base#(className);

/**
 * Generated by KungFuPanda.
 */
@SuppressWarnings("serial")
public class #(className) extends Base#(className)<#(className)> {
    public static final #(className) dao = new #(className)().dao();
}
